version: "3.8"

services:
  web:
    container_name: web
    build: .
    restart: always
    tty: true
    ports:
      - 3000:3000
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    entrypoint: ["npm", "run", "start"]